name: Debug Notary Log

on:
  workflow_dispatch:

jobs:
  get-log:
    runs-on: macos-latest
    steps:
      - name: Fetch Notary Log
        run: |
          xcrun notarytool log "a1df4313-e5aa-4c0d-8aa5-58b429575f89" \
            --apple-id "${{ secrets.AC_USERNAME }}" \
            --password "${{ secrets.AC_PASSWORD }}" \
            --team-id "${{ secrets.AC_TEAM_ID }}"
