name: Debug Notary Log

on:
  workflow_dispatch:

jobs:
  get-log:
    runs-on: macos-latest
    steps:
      - name: Fetch Notary Log
        run: |
          xcrun notarytool log "c7ff1863-9a83-4d70-aa0b-c60ce8c9e77c" \
            --apple-id "${{ secrets.AC_USERNAME }}" \
            --password "${{ secrets.AC_PASSWORD }}" \
            --team-id "${{ secrets.AC_TEAM_ID }}"
