name: Debug Notary Log

on:
  workflow_dispatch:

jobs:
  get-log:
    runs-on: macos-latest
    steps:
      - name: Fetch Notary Log
        run: |
          xcrun notarytool log "f89b442f-33c5-4ccf-a60f-c96b458511ca" \
            --apple-id "${{ secrets.AC_USERNAME }}" \
            --password "${{ secrets.AC_PASSWORD }}" \
            --team-id "${{ secrets.AC_TEAM_ID }}"
